pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url = 'https://www.jitpack.io' } // MPAndroidChart
    }
}
rootProject.name = 'Organic Maps'
include ':app'
include ':sdk'
include ':sdk:maps:world'
include ':app:omaps'
include ':baselineprofile'

