apply plugin: 'com.android.application'
apply from: '../groovy/common-config.gradle'

def googleFirebaseServicesEnabled = project.file('google-services.json').exists()
if (googleFirebaseServicesEnabled) {
  apply plugin: 'com.google.gms.google-services'
  apply plugin: 'com.google.firebase.crashlytics'
}

android {
  namespace 'app.organicmaps'

  buildFeatures {
    buildConfig true
  }

  defaultConfig {
    applicationId "app.organicmaps"
    versionCode 20250305
    versionName "1.0"

    multiDexEnabled true

    buildConfigField 'String', 'REVIEW_URL', '""'

    externalNativeBuild {
      cmake {
        cppFlags '-fexceptions', '-frtti'
        cFlags '-fno-function-sections', '-fno-data-sections', '-Wno-extern-c-compat'
        arguments '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=c++_static',
            '-DSKIP_TESTS=ON', '-DSKIP_TOOLS=ON'
      }
    }
    
    ndk {
        debugSymbolLevel = null
    }
  }

  sourceSets {
    main {
      java.srcDirs = ['src/main/java']
      res.srcDirs = ['src/main/res']
      assets.srcDirs = ['src/main/assets']
    }
    google {
      java.srcDirs = ['src/google/java', 'src/gms/java']
      manifest.srcFile 'src/gms/AndroidManifest.xml'
    }
    fdroid {
      java.srcDirs = ['src/fdroid/java']
      manifest.srcFile 'src/fdroid/AndroidManifest.xml'
    }
    web {
      java.srcDirs = ['src/google/java', 'src/gms/java']
      manifest.srcFile 'src/gms/AndroidManifest.xml'
    }
    huawei {
      java.srcDirs = ['src/google/java', 'src/gms/java']
      manifest.srcFile 'src/gms/AndroidManifest.xml'
    }
    oss { java.srcDirs = ['src/locationOss/java', 'src/oss/java'] }
  }

  flavorDimensions += 'default'

  productFlavors {
    google {
      dimension 'default'
      buildConfigField 'String', 'SUPPORT_MAIL', '"google@organicmaps.app"'
    }

    web {
      dimension 'default'
      applicationIdSuffix '.web'
      versionName = android.defaultConfig.versionName + '-Web'
      buildConfigField 'String', 'SUPPORT_MAIL', '"web@organicmaps.app"'
    }

    fdroid {
      dimension 'default'
      versionName = android.defaultConfig.versionName + '-FDroid'
      buildConfigField 'String', 'SUPPORT_MAIL', '"fdroid@organicmaps.app"'
    }

    oss {
      dimension 'default'
      versionName = android.defaultConfig.versionName + '-OSS'
      buildConfigField 'String', 'SUPPORT_MAIL', '"oss@organicmaps.app"'
    }

    huawei {
      dimension 'default'
      applicationIdSuffix '.huawei'
      versionName = android.defaultConfig.versionName + '-Huawei'
      buildConfigField 'String', 'SUPPORT_MAIL', '"huawei@organicmaps.app"'
    }
  }

  signingConfigs {
    debug {
      storeFile file('debug.keystore')
      storePassword '12345678'
      keyAlias 'debug'
      keyPassword '12345678'
    }
  }

  buildTypes {
    debug {
      applicationIdSuffix '.debug'
      signingConfig signingConfigs.debug
    }
    release {
      minifyEnabled true
      shrinkResources true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.debug
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
    coreLibraryDesugaringEnabled true
  }

  lint {
    checkReleaseBuilds false
    abortOnError false
  }

  androidResources {
    ignoreAssetsPattern = '!.svn:!.git:!.DS_Store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~'
    noCompress = ['txt', 'bin', 'html', 'png', 'json', 'mwm', 'ttf', 'sdf', 'ui', 'config', 'csv', 'spv', 'obj']
  }
}

tasks.register('copyAssets', Copy) {
  from "../../data"
  include "countries.txt"
  include "countries-strings/**"
  include "sound-strings/**"
  include "categories.txt"
  include "classificator.txt"
  include "types.txt"
  include "packed_polygons.bin"
  include "drules_proto*.bin"
  into "src/main/assets"
}

preBuild.dependsOn 'copyAssets'

dependencies {
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

  implementation project(':sdk')
  
  implementation 'androidx.appcompat:appcompat:1.6.1'
  implementation 'androidx.preference:preference:1.2.1'
  implementation 'com.google.android.material:material:1.9.0'
  implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
  implementation 'androidx.car.app:app:1.7.0'
  implementation 'androidx.lifecycle:lifecycle-process:2.9.4'
  implementation 'androidx.work:work-runtime:2.10.1'
  implementation 'com.google.guava:guava:33.4.0-android'
  implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

  googleImplementation 'com.google.android.gms:play-services-location:21.3.0'
  webImplementation 'com.google.android.gms:play-services-location:21.3.0'
  huaweiImplementation 'com.google.android.gms:play-services-location:21.3.0'
  fdroidImplementation 'com.google.android.gms:play-services-location:21.3.0'
  ossImplementation 'androidx.annotation:annotation:1.9.1'
  
  googleImplementation 'com.google.android.gms:play-services-wearable:19.0.0'
  webImplementation 'com.google.android.gms:play-services-wearable:19.0.0'
  huaweiImplementation 'com.google.android.gms:play-services-wearable:19.0.0'
  fdroidImplementation 'com.google.android.gms:play-services-wearable:19.0.0'

  if (googleFirebaseServicesEnabled) {
    implementation platform('com.google.firebase:firebase-bom:33.11.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-crashlytics-ndk'
  }
}
