name: Sideload Builds

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

env:
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

jobs:
  build-phone:
    name: Phone ${{ matrix.flavor }} (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm32, arm64]
        include:
          - flavor: google
            taskFlavor: Google
          - flavor: fdroid
            taskFlavor: Fdroid
          - flavor: oss
            taskFlavor: Oss
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Checkout submodules
        shell: bash
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Configure repository
        shell: bash
        run: ./configure.sh

      - name: Set up Android SDK
        shell: bash
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Phone APK
        working-directory: android
        run: ./gradlew :app:assemble${{ matrix.taskFlavor }}Debug -P${{ matrix.arch }}

      - name: Upload Phone APK
        uses: actions/upload-artifact@v4
        with:
          name: Phone-${{ matrix.flavor }}-${{ matrix.arch }}
          path: android/app/build/outputs/apk/${{ matrix.flavor }}/debug/*.apk

  build-watch:
    name: Watch ${{ matrix.flavor }} (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm32, arm64]
        include:
          - flavor: google
            taskFlavor: Google
          - flavor: fdroid
            taskFlavor: Fdroid
          - flavor: oss
            taskFlavor: Oss
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Checkout submodules
        shell: bash
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Configure repository
        shell: bash
        run: ./configure.sh

      - name: Set up Android SDK
        shell: bash
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Watch APK
        working-directory: android
        run: ./gradlew :app:omaps:assemble${{ matrix.taskFlavor }}Debug -P${{ matrix.arch }}

      - name: Upload Watch APK
        uses: actions/upload-artifact@v4
        with:
          name: Watch-${{ matrix.flavor }}-${{ matrix.arch }}
          path: android/app/omaps/build/outputs/apk/${{ matrix.flavor }}/debug/*.apk